# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  one:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: console.log( "A first hello")
  three:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: console.log( "A more familiar hi")
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - three
